spring:
  datasource:
      url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    stream:
      binders:
        default:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: user
                password: user
                virtual-host: /