spring:
  datasource:
      url: jdbc:mysql://discovery-mysql:3306/discovery
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      binders:
        default:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq
                port: 5672
                username: user
                password: user
                virtual-host: /